### ISSUE TITLE
requesting webpack version

### ISSUE THREAD

**Issue by st-clair-clarke** [cristovao-trevisan/svelte-icon#1]
Hi,
I am using webpack, but your offering uses rollup. Is it possible for us to get a webpack offering?

Thanks

**Comment by cristovao-trevisan** [comment]
Try using the raw loader:
```sh
npm install raw-loader --save-dev
```

Replace the path with your icons folder:
```js
// webpack.config.js

module.exports = {
   //...
  module: {
    rules: [
       // ...
      {
        test: /images\/folder\/.*svg$/i,
        use: 'raw-loader',
      },
    ],
  },
};
```

Let me know if it works so I can put this on the readme

**Comment by cristovao-trevisan** [comment]
The above solution does work, I'm using it now. Added to readme
