### ISSUE TITLE
Vite Config

### ISSUE THREAD

**Issue by dawidmachon** [cristovao-trevisan/svelte-icon#4]
Any idea for Vite config to make it working with Svelte?

**Comment by cristovao-trevisan** [comment]
Sveltekit uses Vite, so it should be the same. Import the icon file as a string with the ?raw option, eg.:
```html
<script>
  import Icon from 'svelte-icon/Icon.svelte';
  import logo from '$lib/img/logo.svg?raw';
</script>

<Icon data={logo} size="20px" />

**Comment by dawidmachon** [comment]
Yeah, my bad. Its working ;P
