### ISSUE TITLE
Regex for removing svg doesn't support line breaks

### ISSUE THREAD

**Issue by MrCelestis** [cristovao-trevisan/svelte-icon#5]
SVGs formatted like this
```
<svg
   width="100"
   height="100"
```
are not parsed by 

```
  $: elements = data
    .replace(/<svg ([^>]*)>/, '')
```

and the svg element is nested in svelte-icon's svg, preventing display.
This regex currently expects a space char to be present after tag start.

Workaround is to preprocess the svg text to convert line breaks to spaces.

**Comment by MrCelestis** [comment]
Wow, that was fast)

**Comment by cristovao-trevisan** [comment]
Just changed the regex to accept space or \n :smile: 
1.3.1 was just published
